"""create edges table

Revision ID: 3c044a602489
Revises: 26fda158abd2
Create Date: 2026-03-14 14:55:56.995977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c044a602489'
down_revision: Union[str, Sequence[str], None] = '26fda158abd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_id'), 'edges', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edges_id'), table_name='edges')
    op.drop_table('edges')
    # ### end Alembic commands ###
