"""add weight and state fields to edges

Revision ID: ed6f99f94216
Revises: 3c044a602489
Create Date: 2026-03-16 18:15:16.102638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6f99f94216'
down_revision: Union[str, Sequence[str], None] = '3c044a602489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('weight', sa.Float(), nullable=False))
    op.add_column('edges', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('edges', sa.Column('activation_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edges', 'activation_count')
    op.drop_column('edges', 'is_active')
    op.drop_column('edges', 'weight')
    # ### end Alembic commands ###
